version: '3'
services:
  http:
    build: ./http
    container_name: http
    ports:
      - "8080:8080"
    volumes:
      - ./app:/app
    depends_on:
      - script

  script:
    build: ./script
    container_name: script
    expose:
      - "9000"
    volumes:
      - ./app:/app
